"""
survey.py — Streamlit survey flow for the cognitive-bias experiment.

Flow:
  Screen 0  CONSENT       — ethics checkbox, must tick before proceeding
  Screen 1  INSTRUCTIONS  — how the survey works
  Screen 2  TRIALS        — 30 binary-choice scenarios, one at a time
  Screen 3  DONE          — thank-you page; data written to Supabase here

Session-state keys used by this module:
  survey_screen          : int 0–3
  participant_id         : str (UUID)
  participant_seed       : int
  scenarios              : list[dict] (generated by scenarios.py)
  trial_idx              : int (current 0-based position in scenarios)
  responses              : list[dict] (accumulates during trials)
  display_time           : float (time.time() when scenario was rendered)
  consent_checked        : bool
"""

import time
import uuid
import random
import datetime
import streamlit as st

from scenarios import generate_participant_scenarios
from storage import insert_responses


def _init_session() -> None:
    """Initialise session-state keys if they do not exist."""
    defaults = {
        "survey_screen": 0,
        "participant_id": None,
        "participant_seed": None,
        "scenarios": None,
        "trial_idx": 0,
        "responses": [],
        "display_time": None,
        "consent_checked": False,
    }
    for key, val in defaults.items():
        if key not in st.session_state:
            st.session_state[key] = val


# ─────────────────────────────────────────────────────────────────────────────
# Screen 0 — Consent
# ─────────────────────────────────────────────────────────────────────────────

def _screen_consent() -> None:
    st.title("Participant Information & Consent")
    st.markdown("""
---
**Purpose of this study**

This survey is part of a school research project investigating how people make decisions
under uncertainty. You will be presented with 30 short scenarios and asked to choose between
two options (A or B). There are no right or wrong answers — we are interested in your
natural judgements.

**What data is collected**

- Your responses (choice A or B) for each scenario.
- The time taken (in milliseconds) to make each choice.
- **No personal information** — no names, email addresses, ages, or any other identifying
  details are collected at any point.

**How your data will be used**

Responses will be analysed anonymously as part of a statistical investigation and may be
included in a school Extended Essay. Your data will not be shared outside this project.

**Voluntary participation**

Participation is entirely voluntary. You may stop at any time by closing this page.
Incomplete sessions will not be stored.

**Duration**

The survey takes approximately 15–20 minutes. Please find a quiet moment to complete it
in one sitting.

**Minors**

If you are under 18, please ensure you have parental or guardian consent to participate,
in accordance with your school's guidelines.

---
""")

    st.session_state["consent_checked"] = st.checkbox(
        "✅  I am a current IB Diploma student. I have read the information above and "
        "I consent to participate in this study.",
        value=st.session_state.get("consent_checked", False),
    )

    if st.button("Start Survey", disabled=not st.session_state["consent_checked"]):
        # Generate a unique ID and seed for this participant
        st.session_state["participant_id"]   = str(uuid.uuid4())
        st.session_state["participant_seed"] = random.randint(0, 2**31 - 1)
        st.session_state["scenarios"] = generate_participant_scenarios(
            st.session_state["participant_seed"]
        )
        st.session_state["trial_idx"]  = 0
        st.session_state["responses"]  = []
        st.session_state["survey_screen"] = 1
        st.rerun()


# ─────────────────────────────────────────────────────────────────────────────
# Screen 1 — Instructions
# ─────────────────────────────────────────────────────────────────────────────

def _screen_instructions() -> None:
    st.title("Instructions")
    st.markdown("""
You will be shown **30 short scenarios**, one at a time. Each scenario describes a situation
and presents two options, labelled **Option A** and **Option B**.

**Your task:** Read each scenario carefully and click the option that you would genuinely
choose in that situation.

- There is **no time limit** — take as long as you need for each question.
- There are **no right or wrong answers** — respond as you naturally would.
- Once you click an option you will move to the next scenario immediately.
  You **cannot go back** to change a previous answer.
- Please complete all 30 scenarios **in one sitting** without interruptions.

A progress indicator at the top of each page shows how many scenarios you have completed.

When you are ready, click **Begin** to start the survey.
""")
    if st.button("Begin →", type="primary"):
        st.session_state["survey_screen"] = 2
        st.session_state["display_time"] = time.time()
        st.rerun()


# ─────────────────────────────────────────────────────────────────────────────
# Screen 2 — Trials
# ─────────────────────────────────────────────────────────────────────────────

def _record_choice(choice: int) -> None:
    """
    Called when the participant clicks Option A (0) or Option B (1).

    Computes reaction time, attaches all feature values, and appends the row
    to st.session_state["responses"].
    """
    rt_ms = max(0, round((time.time() - st.session_state["display_time"]) * 1000))

    idx   = st.session_state["trial_idx"]
    sc    = st.session_state["scenarios"][idx]
    responses = st.session_state["responses"]

    # previous_choice: the participant's last actual response (0 for trial 0)
    prev_choice = responses[-1]["choice"] if responses else 0

    row = {
        # Feature columns
        "trial_index":           sc["trial_index"],
        "bias_type":             sc["bias_type"],
        "frame":                 sc["frame"],
        "expected_value_ratio":  sc["expected_value_ratio"],
        "anchor_value":          sc["anchor_value"],
        "previous_choice":       prev_choice,
        "is_first_trial":        sc["is_first_trial"],
        "reaction_time_ms":      rt_ms,
        # Target
        "choice":                choice,
        # Metadata
        "participant_id":        st.session_state["participant_id"],
        "participant_seed":      st.session_state["participant_seed"],
        "scenario_template_id":  sc["scenario_template_id"],
        "created_at":            datetime.datetime.now(datetime.timezone.utc).isoformat(),
    }
    responses.append(row)
    st.session_state["responses"] = responses
    st.session_state["trial_idx"] = idx + 1

    if st.session_state["trial_idx"] >= len(st.session_state["scenarios"]):
        st.session_state["survey_screen"] = 3
    else:
        st.session_state["display_time"] = time.time()

    st.rerun()


def _screen_trials() -> None:
    idx       = st.session_state["trial_idx"]
    scenarios = st.session_state["scenarios"]
    total     = len(scenarios)

    st.progress(idx / total, text=f"Question {idx + 1} of {total}")
    st.divider()

    sc = scenarios[idx]
    st.markdown(f"### {sc['problem_text']}")
    st.write("")

    col_a, col_b = st.columns(2)
    with col_a:
        st.markdown(
            f"""
            <div style="
                border: 2px solid #4C72B0;
                border-radius: 10px;
                padding: 16px 20px;
                min-height: 120px;
                font-size: 0.97rem;
            ">
            <strong>Option A</strong><br><br>{sc['option_a_text']}
            </div>
            """,
            unsafe_allow_html=True,
        )
        st.write("")
        if st.button("Choose Option A", key=f"btn_a_{idx}", use_container_width=True):
            _record_choice(0)

    with col_b:
        st.markdown(
            f"""
            <div style="
                border: 2px solid #DD8452;
                border-radius: 10px;
                padding: 16px 20px;
                min-height: 120px;
                font-size: 0.97rem;
            ">
            <strong>Option B</strong><br><br>{sc['option_b_text']}
            </div>
            """,
            unsafe_allow_html=True,
        )
        st.write("")
        if st.button("Choose Option B", key=f"btn_b_{idx}", use_container_width=True):
            _record_choice(1)


# ─────────────────────────────────────────────────────────────────────────────
# Screen 3 — Done
# ─────────────────────────────────────────────────────────────────────────────

def _screen_done() -> None:
    # Write data to Supabase exactly once
    if not st.session_state.get("_data_submitted", False):
        success = insert_responses(st.session_state["responses"])
        st.session_state["_data_submitted"] = True
        st.session_state["_submission_ok"] = success

    st.title("Thank You!")
    st.markdown("""
---
You have completed all 30 questions. Your responses have been recorded anonymously.

Your participation is greatly appreciated and will contribute to research on
how people make decisions under uncertainty.

You may now close this tab.

---
""")
    if not st.session_state.get("_submission_ok", True):
        st.warning(
            "⚠️  There was a problem saving your responses to the database. "
            "Please contact the researcher so your data can be recorded manually."
        )


# ─────────────────────────────────────────────────────────────────────────────
# Public entry point
# ─────────────────────────────────────────────────────────────────────────────

def run_survey() -> None:
    """Main entry point called from app.py."""
    _init_session()
    screen = st.session_state["survey_screen"]
    if screen == 0:
        _screen_consent()
    elif screen == 1:
        _screen_instructions()
    elif screen == 2:
        _screen_trials()
    else:
        _screen_done()
